version: 2
dist: bin

builds:
  - binary: bin/taskctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    goarm64:
      - v8.0
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
      - autocomplete/bash_completion.bash
      - autocomplete/zsh_completion.zsh
    allow_different_binary_count: true

source:
  enabled: true

changelog:
  disable: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

brews:
  - commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
    extra_install: |
        bash_completion.install "autocomplete/bash_completion.bash"
        zsh_completion.install "autocomplete/zsh_completion.zsh"
    repository:
      owner: taskctl
      name: homebrew-taskctl


dockers:
  - image_templates:
      - "docker.io/taskctl/taskctl:latest"
      - "ghcr.io/taskctl/taskctl:latest"
      - "docker.io/taskctl/taskctl:{{ .Tag }}"
      - "ghcr.io/taskctl/taskctl:{{ .Tag }}"
    skip_push: auto
    goos: linux
    goarch: amd64

scoops:
  - repository:
      owner: taskctl
      name: scoop-taskctl
    commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
