version: 2
dist: bin

builds:
  - binary: bin/taskctl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    goarm64:
      - v8.0

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE.md
      - README.md
      - autocomplete/bash_completion.bash
      - autocomplete/zsh_completion.zsh
    allow_different_binary_count: true

nfpms:
  - homepage: https://github.com/taskctl/taskctl
    maintainer: Yevhen Terentiev <yevhen.terentiev@gmail.com>
    description: Concurrent task runner and developer's routine tasks automation toolkit
    license: GPL-3.0
    formats:
      - deb
      - rpm

source:
  enabled: true

changelog:
  disable: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

homebrew_casks:
  - commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
    description: Concurrent task runner and developer's routine tasks automation toolkit
    binaries:
      - bin/taskctl
    completions:
      bash: autocomplete/bash_completion.bash
      zsh: autocomplete/zsh_completion.zsh
    repository:
      owner: taskctl
      name: homebrew-taskctl

dockers_v2:
  - images:
      - docker.io/taskctl/taskctl
      - ghcr.io/taskctl/taskctl
    tags:
      - latest
      - "{{ .Tag }}"
    platforms:
      - linux/amd64
      - linux/arm64
    disable: "{{ if .Prerelease }}true{{ else }}false{{ end }}"

scoops:
  - repository:
      owner: taskctl
      name: scoop-taskctl
    commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/taskctl/taskctl
    description: Concurrent task runner and developer's routine tasks automation toolkit
