pipelines:
  build:
    - name: Build "darwin"
      task: build
      env:
        GOOS: darwin
        BIN_OUT: bin/wilson_darwin_amd64
    - name: Build "linux"
      task: build
      env:
        GOOS: linux
        BIN_OUT: bin/wilson_linux_amd64

  release:
    - task: update-cmd-version
    - task: test
      depends_on: update-cmd-version
    - task: push-tag
      depends_on: test

tasks:
  test:
    command:
      - go test ./...

  build:
    command:
      - GOOS=${GOOS} GOARCH=amd64 go build -o ${BIN_OUT} -v main.go

  update-cmd-version:
    command:
      - sed -i '' '/Version:/s/".*"/"'${ARGS}'"/' cmd/cmd.go
      - git add cmd/cmd.go

  push-tag:
    command:
      - git commit -m "Release ${ARGS}"
      - git tag ${ARGS}
      - git push origin master
      - git push origin ${ARGS}
