package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRun(t *testing.T) {
	dir := t.TempDir()

	if err := run(dir); err != nil {
		t.Fatalf("run() returned error: %v", err)
	}

	rootPage, err := os.ReadFile(filepath.Join(dir, "taskctl.md"))
	if err != nil {
		t.Fatalf("expected taskctl.md to exist: %v", err)
	}
	if !strings.Contains(string(rootPage), "modern task runner") {
		t.Errorf("taskctl.md does not contain root Short description")
	}

	if _, err := os.Stat(filepath.Join(dir, "taskctl_run.md")); err != nil {
		t.Errorf("expected taskctl_run.md to exist: %v", err)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("failed to read generated dir: %v", err)
	}

	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			t.Fatalf("failed to read %s: %v", entry.Name(), err)
		}
		if strings.Contains(string(content), "Auto generated by spf13/cobra") {
			t.Errorf("%s contains auto-generated tag, expected DisableAutoGenTag to suppress it", entry.Name())
		}
	}
}
